                                                                                                                                                              ,-------------------.                                                                                             
                                                                ,--------------------.                                                                        |MaitreDuJeu        |               ,----------------------.                                                      
                                                                |Case                |                                                                        |-------------------|               |Tour                  |                                                      
                                           ,----------------.   |--------------------|                                                                        |                   |   ,------.    |----------------------|    ,------------.                                    
                                           |Dé              |   |- x : int           |                                                                        |nom : String       |   |Joueur|    |- numeroDuTour : int  |    |Action      |                                    
                                           |----------------|   |- y : int           |                                                                        |                   |   |------|    |- ordre : List<Entité>|    |------------|                                    
                                           |+ lancer() : int|   |- estObstacle : bool|                                                                        |narrer()           |   `------'    |+ determinerOrdre()   |    |+ executer()|                                    
                                           `----------------'   |- contient : Objet  |                                                                        |                   |               |+ passerAuSuivant()   |    `------------'                                    
                                                                `--------------------'                                                                        |controlerMonstres()|               `----------------------'           |                                          
                                                                                                                                                              `-------------------'                                                  |                                          
                                                                                                                                                                                                                                     |                                          
                                                                                                                                                                                                                                     |                                          
                                                                                                                   ,-----------------------------------.                                                                             |                                          
                                                                                                                   |Personnage                         |                                                                             |                                          
                                                                                                                   |-----------------------------------|                                                                             |                                          
                                                                                                                   |- nom : String                     |   ,-----------------------.                                                 |                                          
,------------------.  ,-------------------------------------------.                                                |- etat : Boolean                   |   |Objet                  |                                                 |                                          
|Carte             |  |Monstre                                    |                                                |- inventaire : Inventaire          |   |-----------------------|           ,--------------------.  ,-------------------------.   ,-------------------------.
|------------------|  |-------------------------------------------|                                                |- equipement : EquipementPersonnage|   |- nom : String         |   ,---.   |Attaquer            |  |SeDeplacer               |   |SEquiper                 |
|- largeur : int   |  |- id : int                                 |                                                |+ getNom() : String                |   |- poids : int          |   |Jeu|   |--------------------|  |-------------------------|   |-------------------------|
|- hauteur : int   |  |- espece : String                          |                                                |+ getEtat() : Boolean              |   |+ getNom() : String    |   |---|   |- attaquant : Entité|  |- personnage : Personnage|   |- personnage : Personnage|
|- cases : Case[][]|  |- caracteristiques : CaractéristiqueMonstre|                                                |+ setNom(nom : String)             |   |+ getPoids() : int     |   `---'   |- cible : Entité    |  |- destination : Case     |   |- objet : Objet          |
|+ afficher()      |  |+ attaquer(cible : Entité)                 |                                                |+ setEtat(etat : Boolean)          |   |+ setNom(nom : String) |           |+ executer()        |  |+ executer()             |   |+ executer()             |
|+ placerElement() |  |+ toString() : String                      |                                                |+ attaquer(cible : Entité)         |   |+ setPoids(poids : int)|           `--------------------'  `-------------------------'   `-------------------------'
`------------------'  `-------------------------------------------'                                                |+ seDeplacer()                     |   |+ toString() : String  |                                                                                            
                                                                                                                   |+ sEquiper(objet : Objet)          |   `-----------------------'                                                                                            
                                                                                                                   |+ ramasser(objet : Objet)          |                                                                                                                        
                                                                                                                   |+ toString() : String              |                                                                                                                        
                                                                                                                   `-----------------------------------'                                                                                                                        
                                                                                                                                                                                                                                                                                
                                                           ,---------------------------------.                                                                                                                                                                                  
                                                           |Caractéristique                  |                                                                                                                                                                                  
                                                           |---------------------------------|                                                                                                                                                                                  
                                                           |- pv : int                       |                                                                                                                                                                                  
                                                           |- force : int                    |                                                                                                                                                                                  
   ,-------------------.                                   |- dexterite : int                |                                                                                                                                                                                  
   |Donjon             |     ,-------------------------.   |- vitesse : int                  |                                                                                    ,------------------------------.                                                              
   |-------------------|     |CaractéristiqueMonstre   |   |- initiative : int               |   ,-----------------------.   ,-----------------------.  ,---------------------.   |Inventaire                    |                                                              
   |- carte : Carte    |     |-------------------------|   |+ getPV() : int                  |   |Classe                 |   |Race                   |  |EquipementPersonnage |   |------------------------------|                                                              
   |- monstres : List  |     |- classeArmure : int     |   |+ getForce() : int               |   |-----------------------|   |-----------------------|  |---------------------|   |- objets : List               |                                                              
   |- joueurs : List   |     |- attaque : String       |   |+ getDexterite() : int           |   |- nom : String         |   |- nom : String         |  |- equipement : List  |   |+ ajouter(objet : Objet)      |                                                              
   |- obstacles : List |     |+ getClasseArmure() : int|   |+ getVitesse() : int             |   |+ bonusCreation() : int|   |+ bonusCreation() : int|  |+ toString() : String|   |+ retirer(objet : Objet)      |                                                              
   |+ miseEnPlace()    |     |+ getAttaque() : String  |   |+ getInitiative() : int          |   |+ toString() : String  |   |+ toString() : String  |  `---------------------'   |+ verifierCapacite() : boolean|                                                              
   |+ commencerCombat()|     |+ toString() : String    |   |+ setPV(pv : int)                |   `-----------------------'   `-----------------------'                            |+ toString() : String         |                                                              
   |+ terminerDonjon() |     `-------------------------'   |+ setForce(force : int)          |                                                                                    `------------------------------'                                                              
   `-------------------'                                   |+ setDexterite(dexterite : int)  |                                                                                                                                                                                  
                                                           |+ setVitesse(vitesse : int)      |                                                                                                                                                                                  
                                                           |+ setInitiative(initiative : int)|                                                                                                                                                                                  
                                                           |+ toString() : String            |                                                                                                                                                                                  
                                                           `---------------------------------'                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                
                                                                              ,-----.   ,--------.   ,--------.   ,--------.   ,----.  ,--------.   ,------.   ,----.                                                                                                           
                                                                              |Clerc|   |Guerrier|   |Magicien|   |Roublard|   |Elfe|  |Halfelin|   |Humain|   |Nain|                                                                                                           
                                                                              |-----|   |--------|   |--------|   |--------|   |----|  |--------|   |------|   |----|                                                                                                           
                                                                              `-----'   `--------'   `--------'   `--------'   `----'  `--------'   `------'   `----'                                                                                                           
